# Generated by Django 2.1 on 2018-09-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'cant be blank', 'invalid': 'invalid choice', 'unique': 'it has to be unique, the name entered already exists'}, help_text='name of the script', max_length=25, unique=True, verbose_name='Script Name')),
                ('script_upload', models.FileField(unique=True, upload_to='uploads/', verbose_name='Script Upload Location')),
                ('version', models.IntegerField(blank=True, null=True, verbose_name="Script's version")),
            ],
        ),
    ]
