# Generated by Django 2.1 on 2018-09-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('ip_address', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'cant be blank', 'invalid': 'invalid choice', 'unique': 'the name entered already exists'}, help_text='name of the test', max_length=25, unique=True, verbose_name='Test Name')),
                ('hosts', models.ManyToManyField(to='jugapp.Host')),
                ('scripts', models.ManyToManyField(to='jugapp.Script', verbose_name='list of scripts')),
            ],
        ),
    ]
