# Generated by Django 2.1 on 2018-09-27 02:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jugapp', '0002_host_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptHostMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugapp.Host')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugapp.Script')),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='test',
            name='scripts',
        ),
        migrations.AddField(
            model_name='test',
            name='mapping',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='jugapp.ScriptHostMapping'),
            preserve_default=False,
        ),
    ]
