# Generated by Django 2.1 on 2018-09-27 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugapp', '0003_auto_20180927_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='mapping',
        ),
        migrations.AddField(
            model_name='scripthostmapping',
            name='test',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jugapp.Test'),
            preserve_default=False,
        ),
    ]
