# Generated by Django 2.1 on 2018-09-28 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugapp', '0004_auto_20180927_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=25)),
                ('settings', models.CharField(max_length=500)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugapp.Host')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugapp.Script')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugapp.Test')),
            ],
        ),
        migrations.RemoveField(
            model_name='scripthostmapping',
            name='host',
        ),
        migrations.RemoveField(
            model_name='scripthostmapping',
            name='script',
        ),
        migrations.RemoveField(
            model_name='scripthostmapping',
            name='test',
        ),
        migrations.DeleteModel(
            name='ScriptHostMapping',
        ),
        migrations.AddField(
            model_name='test',
            name='scripts',
            field=models.ManyToManyField(through='jugapp.Mapping', to='jugapp.Script'),
        ),
    ]
