# Generated by Django 2.1 on 2018-10-03 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jugapp', '0005_auto_20180928_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='author',
            field=models.CharField(default='author name', max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='script',
            name='author',
            field=models.CharField(default='author name', max_length=50),
        ),
        migrations.AddField(
            model_name='script',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='test',
            name='author',
            field=models.CharField(default='author name', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip_address',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='Host IP Address'),
        ),
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(error_messages={'blank': 'cant be blank', 'invalid': 'invalid choice', 'unique': 'it has to be unique, the name entered already exists'}, help_text='Name of the script', max_length=25, unique=True, verbose_name='Script Name'),
        ),
        migrations.AlterField(
            model_name='script',
            name='version',
            field=models.IntegerField(blank=True, null=True, verbose_name="script's version"),
        ),
    ]
