# Generated by Django 2.1 on 2018-10-05 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugapp', '0006_auto_20181003_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('author', models.CharField(default='author name', max_length=50)),
                ('argument_name', models.CharField(blank=True, max_length=30, null=True)),
                ('key', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThreadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('author', models.CharField(default='author name', max_length=50)),
                ('enabled', models.BooleanField(null=True)),
                ('tg_name', models.CharField(blank=True, max_length=30, null=True)),
                ('num_threads', models.IntegerField(blank=True, null=True)),
                ('on_sample_error', models.CharField(blank=True, max_length=10, null=True)),
                ('continue_forever', models.BooleanField(null=True)),
                ('loops', models.CharField(blank=True, max_length=6, null=True)),
                ('ramp_time', models.CharField(blank=True, max_length=7, null=True)),
                ('scheduler', models.BooleanField(null=True)),
                ('duration', models.CharField(blank=True, max_length=7, null=True)),
                ('delay', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='script',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'Unknown'), ('uploaded', 'Uploaded'), ('pip', 'Parse In Progress'), ('parsed', 'Parsed'), ('vip', 'Validation In Progress'), ('eip', 'Edit in Progress'), ('ready', 'Ready')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'Unknown'), ('created', 'Created'), ('eip', 'Edit in Progress'), ('ready', 'Ready'), ('tip', 'Test In Progress')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threadgroup',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugapp.Script'),
        ),
        migrations.AddField(
            model_name='argument',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugapp.Script'),
        ),
    ]
