# Generated by Django 2.1 on 2018-11-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugapp', '0007_auto_20181005_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='event_log',
            field=models.TextField(blank=True, help_text='details of on going event - to be used in conjunction with status', max_length=256, null=True, verbose_name='latest event'),
        ),
        migrations.AlterField(
            model_name='script',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Unknown'), (1, 'Uploaded'), (2, 'Parsing'), (3, 'Validating'), (4, 'Ready')], default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Unknown'), (1, 'Created'), (2, 'Ready'), (3, 'Started'), (4, 'Stopped'), (5, 'Analysis')], default=0, max_length=10, null=True),
        ),
    ]
